<?php

/**
 * @file
 * Functions to support theming in the olivero_hijo theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function olivero_hijo_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function olivero_hijo_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function olivero_hijo_preprocess_node(&$variables) {

}
